# -*- coding: utf-8 -*-
"""Create_hole.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J9RXcUHMrguSHs6-hkIaX9rVXeZvMrZh
"""

import numpy as np
import matplotlib.pyplot as plt
import time
import cv2

# from google.colab import drive
# drive.mount('/content/drive')

"""## Create a hole in a picture

To create a hole, change the path, and run the two cells below. 
In the second cell, you can draw rectangle to create holes.
"""

imgpath = "./fox1.jpg"

# For a jpg, jpeg or png picture
img = cv2.imread(imgpath)

# For a picture already in npy
#img = np.load(imgpath)
# img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

#Resize if needed
# img = cv2.resize(img,None,fx=0.2, fy=0.2, interpolation = cv2.INTER_CUBIC)


plt.imshow(img)
plt.axis("off")
plt.show()
#cv2.waitKey(0)
#cv2.destroyAllWindows()

boxes = []
counter = 0
while True:
    def on_mouse(event, x, y, flags, params):
        global boxes, img, counter

        if event == cv2.EVENT_LBUTTONDOWN:
            #print 'Start Mouse Position: '+str(x)+', '+str(y)
            boxes.append((x, y))

        elif event == cv2.EVENT_LBUTTONUP:
            #print 'End Mouse Position: '+str(x)+', '+str(y)
            ebox = (x, y)
            boxes.append((x, y))
            print(boxes)
            img = cv2.rectangle(img, boxes[0], boxes[1], [0, 0, 0], thickness=-1)
            boxes = []
            counter += 1

    cv2.namedWindow('Image')
    cv2.setMouseCallback('Image', on_mouse, 0)
    cv2.imshow('Image',img)

    if cv2.waitKey(1) & 0xFF == ord('q'):
        cv2.destroyAllWindows()
        cv2.imwrite("./created_.jpg", img)
        break

cv2.imwrite("result_jerusalem.jpg", img)

img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
np.save("./rond_creux.npy", img)

type(range(5))
N=50
sum(set(np.arange(0,N,3)).union(set(np.arange(0,N,5))))

a=set([1,2,3,4,5])

a = 0
b = 0
result = 0
while (a<N) & (b<N):
    if a<b:
        a += 3
        if a !=b:
            result += a
    else:
        b += 5
        if b != a:
            result += b
print(result)

